wuxi/urls.py
from django.contrib import admin
from django.urls import path
from django.conf import settings

from django.conf.urls.static import static
from novelas.views import home_view,chapter_view,novel_view,genero_view,search_view

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',home_view, name="home-view"), 
    path('<slug:novelname>/capitulo-<int:num>/',chapter_view, name="chapter-view"),
    path('<slug:novelname>/capitulos/<int:amount>/',novel_view, name="novel-view"),
    path('genero/<slug:genero>/<int:pagina>/',genero_view, name="genero-view"),
    path('resultado_busqueda',search_view, name="search-view"),
    
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

novelas/models.py
from django.db import models
from django.conf import settings
from django.urls import reverse
from datetime import datetime, timezone
from django.utils.text import slugify




class Generos(models.Model):
    
    genero = models.CharField(max_length=300,blank=True,null=True)
    genre = models.CharField(max_length=300,blank=True,null=True)
    genero_slug = models.CharField(max_length=300,blank=True,null=True,default="accion")

    def get_genero_slug_url(self):
        return reverse("genero-view",kwargs={'pagina':0, 'genero':self.genero_slug})
    def __str__(self):
        return  self.genero

class Novelas(models.Model):
    
    categorias = [
    ('NC', 'Novela China'),
    ('NJ', 'Novela Japonesa'),
    ('NK', 'Novela Koreana'),
    ]
    titulo = models.CharField(max_length=50,null=False,blank=False)
    slug_titulo = models.CharField(max_length=50,null=False,blank=False)
    autor = models.CharField(max_length=50,null=False,blank=False)
    traductor = models.CharField(max_length=50,null=True,blank=True)
    estado = models.CharField(max_length=50,null=True,blank=True,default='En curso')
    categoria = models.CharField(max_length=50,null=False,blank=False,choices = categorias)
    sinopsis = models.TextField(null=False,blank=False)
    generos = models.ManyToManyField(Generos)
    img = models.ImageField(upload_to="portadas_novelas",blank=True)
    first_chapter = models.URLField(null=True,blank=True)

    def __str__(self):
        return self.titulo

    def get_novel_url(self):
        
        novelname = self.slug_titulo
        return reverse("novel-view",kwargs={'novelname':novelname , 'amount': 0 })

class allchaps(models.Model):
    nombre = models.CharField(max_length=50,null=False,blank=False)
    contenido = models.TextField(null=False,blank=False)
    num = models.IntegerField(null=False,blank=False)
    nota = models.CharField(max_length=50,null=True,blank=True)
    novel_info = models.ForeignKey('Novelas', on_delete=models.SET_NULL, null=True, blank=True)
    fecha = models.DateTimeField(null = True,blank = False)
    url = models.URLField(null = True , blank = True)
    

    def get_chapter_as_list(self):
        
        return self.contenido.split('\n\n')

    def get_chapter_url(self):
        
        novelname = self.novel_info.slug_titulo
        return reverse("chapter-view",kwargs={'num':self.num , 'novelname':novelname})

    def get_novel_url(self):
        
        novelname = self.novel_info.slug_titulo
        return reverse("novel-view",kwargs={'novelname':novelname , 'amount': 0 })


    def get_posted_time(self):
        
        time = datetime.now(timezone.utc)
        updated_for = (time - self.fecha)
        if updated_for.days == 0:
            if not updated_for.seconds // 3600 > 0:
                if not updated_for.seconds // 60 > 0:
                    updated_for = str(updated_for.seconds) + " segundos"
                else:
                    updated_for = str((updated_for.seconds // 60)) + " minutos"
            else:
                updated_for = str((updated_for.seconds // 3600)) + " horas"

        else:
            updated_for = str(updated_for.days) + " dias"
        return updated_for

    def get_next_chapter(self):

        novelname = slugify(self.novel_info.titulo)
        return reverse("chapter-view",kwargs={'num':(self.num + 1), 'novelname':novelname})

    def get_prev_chapter(self):

        novelname = slugify(self.novel_info.titulo)
        return reverse("chapter-view",kwargs={'num':(self.num - 1), 'novelname':novelname})

    

        

    

        


class Comentarios(models.Model):
    comentario = models.TextField(null=False,blank=False)
    chapter = models.ForeignKey('allchaps', on_delete=models.CASCADE, null=True, blank=True)
    usuario = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, null=True, blank=True)
    fecha = models.DateTimeField(null = True,blank = False)


# Create your models here.

templates/busqueda.html
<html>
<title>Busqueda:{{busqueda}} - novelas en español - Wuxi novelas</title>
<meta charset="UTF-8">
{% load static %}
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="{% static 'css/w3.css' %}">
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Karma">
<style>
body,h1,h2,h3,h4,h5,h6 {font-family: "Karma", sans-serif}
.w3-bar-block .w3-bar-item {padding:20px}
</style>
<body>

<!-- Navbar (sit on top) -->
<div class="w3-top">
    <div class="w3-bar w3-white w3-card" id="myNavbar">
      <a href="{% url 'home-view' %}" class="w3-bar-item w3-button w3-wide" ><img class ="logowuxi" src="{% static 'img/wuxi.png' %}" ></img></a>
      <!-- Right-sided navbar links -->
      <div class="w3-right w3-hide-small">
        <a href="{% url 'home-view' %}" class="w3-bar-item w3-button" style="margin-top: 20px;">Inicio</a>
        
      </div>
      
    </div>
  </div>
  
<!-- !PAGE CONTENT! -->
<div class="w3-main w3-content w3-padding" style="max-width:1200px;margin-top:100px">
  <h1 style="margin-left: 40%;margin-top: -60px;">{{nombre}}</h1>

  <!-- First Photo Grid-->
  {% for novela in novelas %}
  {% if forloop.first %}<div class="w3-row-padding w3-padding-16 w3-center" id="food">{% endif %}
    <div class="w3-quarter">
      <a href="{{novela.get_novel_url}}"><img src="{{novela.img.url}}" alt="Sandwich" style="width:100%"></a>
      <a href="{{novela.get_novel_url}}" style="text-decoration: none;"><h3>{{novela.titulo}}</h3></a>
    </div>
      {% if forloop.counter|divisibleby:4 %}</div><div class="w3-row-padding w3-padding-16 w3-center" id="food">{% endif %}
      {% if forloop.last %}</div>{% endif %}
    {% endfor %}
  </div>
  
  

  <!-- Pagination -->
  <div class="w3-center w3-padding-32">
    <div class="w3-bar">
      <a href="{% url 'search-view' %}?busqueda={{busqueda}}&page=0" class="w3-bar-item w3-button w3-hover-black " >«</a>
      {% for page in paginator %}
      <a href="{% url 'search-view' %}?busqueda={{busqueda}}&page={{page}}" class="w3-bar-item w3-{% if page == pagina %}black w3-button {% else %}button w3-hover-black{% endif %}">{{page}}</a>
      {% endfor %}
      <a href="{% url 'search-view' %}?busqueda={{busqueda}}&page={{max_pag}}" class="w3-bar-item w3-button w3-hover-black">»</a>
    </div>
  </div>
  
  <hr id="about">
  <footer class="w3-container w3-teal w3-center w3-margin-top">
    <p>&copy; Copyright <strong>Wuxi Novelas</strong>. Todos los derechos reservados</p>
  </footer>
<!-- End page content -->
</div>



</body>
</html>

templates/chapter.html
<!DOCTYPE html>
<html lang="es" class="translated-ltr">
<head>
  {% load static %}
  <meta charset="utf-8">
  <title>{{chapter.novel_info.titulo}} - Capitulo {{chapter.num}} - novela en español - Wuxi novelas</title>
  <meta content="width=device-width, initial-scale=1.0" name="viewport">
  <meta content="" name="keywords">
  <meta content="" name="description">
  
  <link href="{% static 'css/chaptercss.css' %}" rel="stylesheet">
  
  <link href="https://fonts.googleapis.com/css?family=Roboto:100,300,400,500,700,900&display=swap" rel="stylesheet">

  <link href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
  
</head>

<body>

  <nav class="navbar navbar-inverse">
    <div class="container">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-collapse-3">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="{% url 'home-view' %}" style="color: white; font-size: 26px; ">Wuxi Novelas</a>
      </div>
  
      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse" id="navbar-collapse-3">
        <ul class="nav navbar-nav navbar-right" >
          <li><a href="{% url 'home-view' %}" style="color:white;">Inicio</a></li>
          
          
          <li>
            <a class="btn btn-default btn-outline btn-circle"  data-toggle="collapse" href="#nav-collapse3" aria-expanded="false" aria-controls="nav-collapse3" style="color:white;">Buscar</a>
          </li>
        </ul>
        <div class="collapse nav navbar-nav nav-collapse" id="nav-collapse3">
          <form class="navbar-form navbar-right" role="search" method="GET" action="{% url 'search-view' %}">
            <div class="form-group">
              <input type="text" class="form-control" placeholder="Buscar novelas" name="busqueda" id="search" autocomplete="off" />
              <input type="text" hidden name="page" value="0">
            </div>
            <button type="submit" class="btn btn-danger"><span class="glyphicon glyphicon-search" aria-hidden="true"></span></button>
          </form>
        </div>
      </div><!-- /.navbar-collapse -->
    </div><!-- /.container -->
  </nav><!-- /.navbar -->

  <div class="todo">
    
  <div class="toggle"></div>
  <div class="content" style="font-family: Arial, sans-serif, serif ;font-size: 18px;" >
    <div class="buttons-group">
      <a href="{{chapter.get_prev_chapter}}" class="previous" ><span class="glyphicon glyphicon-chevron-left"></span></a>
      <a href="{{chapter.get_next_chapter}}" class="next"><span class="glyphicon glyphicon-chevron-right"></span></a>
      
    </div>
    <div id="google_translate_element"></div>
    <br><br>
    <h4><a href="{{chapter.get_novel_url}}">{{chapter.novel_info.titulo}}</a></h4>
    <h2>{{chapter.nombre}}</h2>
    <div style="font-family: Merriweather,serif;">
    {% for chap in chapter.get_chapter_as_list %}
      {{ chap|linebreaks }}<br>
    {% endfor %}
    </div>
    
   
  </div>

  <div class="buttons-group-bottom">
    <a href="{{chapter.get_prev_chapter}}" class="previous" ><span class="glyphicon glyphicon-chevron-left"></span></a>
    <a href="{{chapter.get_next_chapter}}" class="next"><span class="glyphicon glyphicon-chevron-right"></span></a>
  </div>
</div>

          
        
    
   
  
    
    
    
  <script src="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>
  <script src="https://code.jquery.com/jquery-3.3.1.js"></script>
  <script src="{% static 'js/chapterjs.js' %}"></script>
  <script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
  <script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/js/bootstrap.min.js"></script>
  <script src="//code.jquery.com/jquery-1.11.1.min.js"></script>
  
  <script type="text/javascript" src="//translate.google.com/translate_a/element.js?cb=googleTranslateElementInit"></script>

  <script type="text/javascript">
    function googleTranslateElementInit() {
      new google.translate.TranslateElement({pageLanguage: 'en', layout: google.translate.TranslateElement.InlineLayout.SIMPLE}, 'google_translate_element');
    }
    </script>
  

</body>
</html>

templates/generos.html
<html>
<title>{{nombre}} en español - Wuxi novelas</title>
<meta charset="UTF-8">
{% load static %}
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="{% static 'css/w3.css' %}">
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Karma">
<style>
body,h1,h2,h3,h4,h5,h6 {font-family: "Karma", sans-serif}
.w3-bar-block .w3-bar-item {padding:20px}
</style>
<body>

<!-- Navbar (sit on top) -->
<div class="w3-top">
    <div class="w3-bar w3-white w3-card" id="myNavbar">
      <a href="{% url 'home-view' %}" class="w3-bar-item w3-button w3-wide" ><img class ="logowuxi" src="{% static 'img/wuxi.png' %}" ></img></a>
      <!-- Right-sided navbar links -->
      <div class="w3-right w3-hide-small">
        <a href="{% url 'home-view' %}" class="w3-bar-item w3-button" style="margin-top: 20px;margin-right: 20px;text-decoration: none;">Inicio</a>
        
      </div>
      
    </div>
  </div>
  
<!-- !PAGE CONTENT! -->
<div class="w3-main w3-content w3-padding" style="max-width:1200px;margin-top:100px">
  <h1 style="margin-left: 40%;margin-top: -60px;">{{nombre}}</h1>

  <!-- First Photo Grid-->
  {% for novela in novelas %}
  {% if forloop.first %}<div class="w3-row-padding w3-padding-16 w3-center" id="food">{% endif %}
    <div class="w3-quarter">
      <a href="{{novela.get_novel_url}}"><img src="{{novela.img.url}}" alt="Sandwich" style="width:100%"></a>
      <a href="{{novela.get_novel_url}}" style="text-decoration: none;"><h3>{{novela.titulo}}</h3></a>
    </div>
      {% if forloop.counter|divisibleby:4 %}</div><div class="w3-row-padding w3-padding-16 w3-center" id="food">{% endif %}
      {% if forloop.last %}</div>{% endif %}
    {% endfor %}
  </div>
  
  

  <!-- Pagination -->
  <div class="w3-center w3-padding-32">
    <div class="w3-bar">
      <a href="{% url 'genero-view' genero 0 %}" class="w3-bar-item w3-button w3-hover-black " >«</a>
      {% for page in paginator %}
      <a href="{% url 'genero-view' genero page %}" class="w3-bar-item w3-{% if page == pagina %}black w3-button {% else %}button w3-hover-black{% endif %}">{{page}}</a>
      {% endfor %}
      <a href="{% url 'genero-view' genero max_pag %}" class="w3-bar-item w3-button w3-hover-black">»</a>
    </div>
  </div>
  
  <hr id="about">
  <footer class="w3-container w3-teal w3-center w3-margin-top">
    <p>&copy; Copyright <strong>Wuxi Novelas</strong>. Todos los derechos reservados</p>
  </footer>
<!-- End page content -->
</div>



</body>
</html>

templates/novelpage.html
<!DOCTYPE html>
<html>
<title>{{novel.titulo}} novela en español - Wuxi novelas</title>
<meta charset="UTF-8">
{% load static %}
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="{% static 'css/w3.css' %}">
<link rel='stylesheet' href='https://fonts.googleapis.com/css?family=Roboto'>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>

<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>

<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
<style>
html,body,h1,h2,h3,h4,h5,h6 {font-family: "Roboto", sans-serif}
</style>
<script type="text/javascript">
  function googleTranslateElementInit() {
    new google.translate.TranslateElement({pageLanguage: 'en', layout: google.translate.TranslateElement.InlineLayout.SIMPLE}, 'google_translate_element');
  }
  </script>

<body class="w3-light-grey">
 <!-- Navbar (sit on top) -->
<div class="w3-top">
  <div class="w3-bar w3-white w3-card" id="myNavbar">
    <a href="{% url 'home-view' %}" class="w3-bar-item w3-button w3-wide" ><img class ="logowuxi" src="{% static 'img/wuxi.png' %}" ></img></a>
    <!-- Right-sided navbar links -->
    <div class="w3-right w3-hide-small">
      
      <a href="{% url 'home-view' %}" class="w3-bar-item w3-button" style="margin-top: 20px;margin-right: 20px;text-decoration: none;">Inicio</a>
      
    </div>
    
  </div>
</div>



<!-- Page Container -->
<div class="w3-content w3-margin-top" style="max-width:1350px;">

  <!-- The Grid -->
  <div class="w3-row-padding">
  
    <!-- Left Column -->
    <div class="w3-third" >
    
      <div class="w3-white w3-text-grey w3-card-4">
        <div class="w3-display-container">
          <img src="{{novel.img.url}}" style="width:100%;height: 400px" alt="Avatar">
          
        </div>
        <div class="w3-container">
          <br>
          <p><i class="fa fa-pencil fa-fw w3-margin-right w3-large w3-text-teal"></i>{{novel.autor}}</p>
          <p><i class="fa fa-bars fa-fw w3-margin-right w3-large w3-text-teal"></i>{{novel.get_categoria_display}}</p>
          <p><i class="fa fa-calendar fa-fw w3-margin-right w3-large w3-text-teal"></i>{{novel.estado}}</p>
          <p><i class="fa fa-user fa-fw w3-margin-right w3-large w3-text-teal"></i>{{novel.traductor}}</p>
          <hr>

          <p class="w3-large w3-text-theme"><b><i class="fa fa-asterisk fa-fw w3-margin-right w3-text-teal"></i>Generos</b></p>
          
          {% for genero in novel.generos.all %}
          <span>  {{genero}} </span>
          <div class="w3-light-grey w3-round-xlarge">
            <div class="w3-round-xlarge w3-teal" style="height:24px;width:100%"></div>
          </div>
          <br>
          {% endfor %}
          
          <br>

          
        </div>
      </div><br>

    <!-- End Left Column -->
    </div>

    <!-- Right Column -->
    <div class="w3-twothird">
    
      <div class="w3-container w3-card w3-white w3-margin-bottom">
        <h2 class="w3-text-grey w3-padding-16"><i class="fa fa-book fa-fw w3-margin-right w3-xxlarge w3-text-teal"></i>{{novel.titulo}}</h2>
        <div id="google_translate_element"></div>
        <hr>
        
        <div class="w3-container">
          <h5 class="w3-text-teal"><b>Sinopsis</b></h5>
          
          <p>{{novel.sinopsis|linebreaks}}</p>
          <hr>
          <hr>
        </div>
       
       
      </div>

      <div class="w3-container w3-card w3-white">
        <section id="tabs" class="project-tab">
          <div class="container">
              <div class="row">
                  <div class="col-md-12">
                    <br>
                      <nav>
                          <div class="nav nav-tabs nav-fill" id="nav-tab" role="tablist">
                              
                              
                              {% for tab in tabs%}
                              <a class="nav-item nav-link {% if chapter_page == tab %} active {% endif %}" id="nav-contact-tab"  href="{% url 'novel-view' slug_novel tab %}" role="tab" aria-controls="nav-contact" >{% widthratio  tab 1 50 %}-{% widthratio  tab|add:'1' 1 50 %}</a>
                              {% endfor %}
                            </div>
                      </nav>
                      <div class="tab-content" id="nav-tabContent">
                          <div class="tab-pane fade show active" id="nav-home" role="tabpanel" aria-labelledby="nav-home-tab">
                              <table class="table" cellspacing="0" >
                                  
                                  <tbody>
                                    {% for chapter in chapters %}
                                      {% if forloop.first %}<tr>{% endif %}
                                        <td><a href="{{chapter.get_chapter_url}}">Capitulo {{chapter.num}}</a></td>
                                      {% if forloop.counter|divisibleby:5 %}</tr><tr>{% endif %}
                                      {% if forloop.last %}</tr>{% endif %}
                                    {% endfor %}
                
                                  </tbody>
                              </table>
                          </div>
                         
                      </div>
                  </div>
              </div>
          </div>
      </section>
       
        
      </div>
      
      </div>

    <!-- End Right Column -->
    </div>
    
  <!-- End Grid -->
  </div>
  
  <!-- End Page Container -->
</div>

<footer class="w3-container w3-teal w3-center w3-margin-top">
  <p>&copy; Copyright <strong>Wuxi Novelas</strong>. Todos los derechos reservados</p>
</footer>

<script type="text/javascript" src="//translate.google.com/translate_a/element.js?cb=googleTranslateElementInit"></script>

</body>
</html>